name: 'Batman'
description: 'Are you Batman or Bruce Wayne ? Use your commits history to find out !'
inputs:
  username_id:
    description: 'Github user id'
    required: true
  day_start:
    description: 'Hour of the day start'
    required: true
  day_end:
    description: 'Hour of the day end'
    required: true
  github_token:
    description: 'GitHub access token'
    required: false
    default: ${{ github.token }}
outputs:
  identity:
    description: 'Your identity based on your commit hours'
runs:
  using: 'node16'
  main: 'dist/index.js'